theme: jekyll-theme-minimal
layout: default
show_downloads: true
github:
  zip_url: https://github.com/k1mby/style-transfer/archive/master.zip
  tar_url: https://github.com/k1mby/style-transfer/archive/master.tar.gz
